### ISSUE TITLE
An error when running the  test.lua without GPU

### ISSUE THREAD

**Issue by cicido** [xunhuang1995/AdaIN-style#19]
# th test.lua -content input/content/cornell.jpg -style input/style/woman_with_hat_matisse.jpg
{
  content : "input/content/cornell.jpg"
  contentDir : ""
  outputDir : "output"
  styleSize : 512
  saveExt : "jpg"
  vgg : "models/vgg_normalised.t7"
  gpu : 0
  saveOriginal : false
  crop : false
  preserveColor : false
  alpha : 1
  contentSize : 512
  mask : ""
  styleDir : ""
  decoder : "models/decoder.t7"
  style : "input/style/woman_with_hat_matisse.jpg"
  styleInterpWeights : ""
}
/home/dxp/torch/install/bin/luajit: /home/dxp/torch/install/share/lua/5.1/trepl/init.lua:389: module 'cudnn' not found:No LuaRocks module found for cudnn
	no field package.preload['cudnn']
	no file '/root/.luarocks/share/lua/5.1/cudnn.lua'
	no file '/root/.luarocks/share/lua/5.1/cudnn/init.lua'

**Comment by cicido** [comment]
machine version(I use a virtural machine)
# cat /proc/version
Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Nov 19 22:10:57 UTC 2015

**Comment by cicido** [comment]
where I change the LuaJIT to Lua5.2， I got another error:
torch/install/share/lua/5.2/trepl/init.lua:389: module 'unsup' not found:No LuaRocks module found for unsup
	no field package.preload['unsup']
	no file '/root/.luarocks/share/lua/5.2/unsup.lua'
	no file '/root/.luarocks/share/lua/5.2/unsup/init.lua'

**Comment by xunhuang1995** [comment]
The code was depended on "unsup" module. I just removed the dependency and you should be able to run the newest code without error.

**Comment by mazard** [comment]
I'm experiencing the same problem. How can I change the LuaJIT to Lua5.2?

**Comment by mazard** [comment]
Ok, checking test.lua I saw there is a parameter not specified in the reference.
You just have to use -gpu -1 in the command line.

I take the opportunity to say thank you for sharing! your system is totally awesome!
