### ISSUE TITLE
backward on std_net

### ISSUE THREAD

**Issue by xshwen** [xunhuang1995/AdaIN-style#24]
I am wondering that why  are you setting  std_gradInput_centered = self.std_net:backward(input_view, std_grad) but not std_net:backward(input_centered, std_grad) in StyleINLossModule.lua(line 114) file. I would appreciate it very much if you can give some detailed explanation about how to get the std_gradInput.

**Comment by xunhuang1995** [comment]
Thanks for pointing it out. This is a bug. I just fixed it
