### ISSUE TITLE
Installing dep unsup?

### ISSUE THREAD

**Issue by Sugarbank** [xunhuang1995/AdaIN-style#3]
Hi guys I think I installed unsup dep on mac osx but still getting error:
th test.lua -content input/content/cornell.jpg -style input/style/woman_with_hat_matisse.jpg
/Users/zSUGARBANK/torch/install/bin/luajit: ...rs/zSUGARBANK/torch/install/share/lua/5.1/trepl/init.lua:389: module 'unsup' not found:No LuaRocks module found for unsup

Here's my unsup install log, maybe it's being installed to the wrong place?Any ideas?

Christians-iMac:install zSUGARBANK$  luarocks install /Users/zSUGARBANK/Desktop/unsup-0.1-0.rockspec 
Using /Users/zSUGARBANK/Desktop/unsup-0.1-0.rockspec... switching to 'build' mode
Cloning into 'unsup'...
remote: Counting objects: 39, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 39 (delta 5), reused 14 (delta 1), pack-reused 0
Unpacking objects: 100% (39/39), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/usr/local/bin/.." -DCMAKE_INSTALL_PREFIX="/usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0" && make
   
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_unsup-0.1-0-5870/unsup/build
Scanning dependencies of target unsup
[ 50%] Building C object CMakeFiles/unsup.dir/init.c.o
[100%] Linking C shared module libunsup.so
[100%] Built target unsup
cd build && make install
[100%] Built target unsup
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lib/libunsup.so
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/AutoEncoder.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/ConvPsd.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/Diag.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/FistaL1.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/LinearFistaL1.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/LinearPsd.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/SparseAutoEncoder.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/SpatialConvFistaL1.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/UnsupModule.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/UnsupTrainer.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/init.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/kmeans.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/pca.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/psd.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/topo-kmeans.lua
-- Installing: /usr/local/lib/luarocks/rocks-5.2/unsup/0.1-0/lua/unsup/whitening.lua
Updating manifest for /usr/local/lib/luarocks/rocks-5.2
unsup 0.1-0 is now built and installed in /usr/local (license: BSD)

Thanks so much

**Comment by Sugarbank** [comment]
Also check this, looks like it's installed?

Christians-iMac:AdaIN-style-master zSUGARBANK$ luarocks list
Warning: Failed loading manifest for /Users/zSUGARBANK/.luarocks/lib/luarocks/rocks-5.2: /Users/zSUGARBANK/.luarocks/lib/luarocks/rocks-5.2/manifest: No such file or directory

Installed rocks:
----------------

autograd
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

cwrap
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

luaffi
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

nn
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

nninit
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

optim
   1.0.5-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

paths
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

sys
   1.1-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

torch
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

unsup
   0.1-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

xlua
   1.1-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

**Comment by xunhuang1995** [comment]
Hmm I didn't encounter this issue so sorry I can't provide much help. One workaround is to comment out Line 2 and Line 51-64  in `lib/utils.lua`. Since unsup is only used during *color-preserved style transfer*, the other part of code can be run without problem.

**Comment by Sugarbank** [comment]
Ah that's a good workaround.Thankyou:)

**Comment by sanjeev342** [comment]
I had to comment out lines 2, 181, and 193 in test.lua also for it to work. Cheers.
