### ISSUE TITLE
The situation of training

### ISSUE THREAD

**Issue by dovanchan** [xunhuang1995/AdaIN-style#5]
HI
     Thanks for your contribution。Can I ask when you will update the training way?Can you tell us the message about the time and memory usage when training;The biggest breakthrough of your reserch is in the transfer efficiency,so I hope see more statistical data;
In a word，you research looks amazing!!!!
Hoping for your update!!!

**Comment by xunhuang1995** [comment]
Thanks for your interests in my work!

Plan to update training code: Recently I'm quite busy with my classes (I'm a first-year PhD anyway :-)), but I will try to clean up the training code in half a month or so.

Details for training: With a single Pascal Titan X, it takes about one week for the network to fully converge and half a day to get reasonably good results. The memory usage depends on the batch size. I use batch size = 8 and it requires ~10G memory, but smaller batch size can give you similar results.
