### ISSUE TITLE
Strange Result without protecting the detail.

### ISSUE THREAD

**Issue by dovanchan** [xunhuang1995/AdaIN-style#8]
<img width="714" alt="222" src="https://cloud.githubusercontent.com/assets/26133721/24607192/226486e4-18a3-11e7-96a2-93096f54004d.png">
![girl_stylized_5](https://cloud.githubusercontent.com/assets/26133721/24607197/265227fc-18a3-11e7-8ed1-e70da52cac54.jpg)
![girl_stylized_9](https://cloud.githubusercontent.com/assets/26133721/24607198/298867ba-18a3-11e7-87b7-0e25872975cb.jpg)
![photo_stylized_5](https://cloud.githubusercontent.com/assets/26133721/24607208/31b2c412-18a3-11e7-859e-cabe7484a0c9.jpg)

The result is so broken,I think a great art style should  protect more detail(such as eyes ,nose ,mouth)...So I suggest you can reference this website:
https://www.reddit.com/r/deepdream/comments/4ky9zp/scarlett_johansson_x4/?st=j11ntfv1&sh=fb7f6881

It's talking about how to protect detail and get a great art result;http://imgur.com/a/cH91s

![image](https://cloud.githubusercontent.com/assets/26133721/24607402/07afc268-18a4-11e7-802e-702e0a772f14.png)

I hold you can try to improve the algorithm for protecting detail ,It will be very beautiful,
It will product a real art like this: http://imgur.com/a/cH91s
Thank you

**Comment by dovanchan** [comment]
Hi,One more question:
-crop: Center crop both content and style images beforehand ,
What 's the meaning of crop???When should I use it?

**Comment by gsssrao** [comment]
@dovanchan You need to use `-crop` when you would like to do a center crop before scaling (If you use `-contentSize 0` or `-styleSize 0` scaling will not take place for content and style images respectively). 
Say you have a content image of size WxH (say 640x480). Then, using `-crop` will crop the image into a size of min(W,H) x min(W,H) (i.e 480x480) about the center of the image. The same happens to style.

**Comment by gsssrao** [comment]
@dovanchan Regarding your first query, have you tried the newer model i.e using `-decoder models/decoder-content-similar.t7`. I seem to get better results with it for faces. Also, experiment with `-alpha`. Keeping smaller alpha like 0.5-0.6 along with the newer decoder model produces better results. Try it!!

Besides this for more improvement, I think that the network will have to retrained with more face data.

**Comment by dovanchan** [comment]
!!!! I can't agree with you anymore!

![photo_stylized_te3](https://cloud.githubusercontent.com/assets/26133721/24615102/ed3baec6-18bf-11e7-8557-497038fc8ba5.jpg)
![photo_stylized_te4](https://cloud.githubusercontent.com/assets/26133721/24615113/f6d809d4-18bf-11e7-80ed-4a56f4c8f01b.jpg)
Here is the result with face ;It's strange～

**Comment by dovanchan** [comment]
@gsssrao  Have you ever known about dreamscope?https://dreamscopeapp.com/ 
These results from ds are amazing~~

![image](https://cloud.githubusercontent.com/assets/26133721/24615361/a1040fca-18c0-11e7-9b42-6ebdf7bcffbb.png)

Do you have some implement can get close to it?or we can share the great parameters in neural style each other ;

**Comment by gsssrao** [comment]
@dovanchan They look cool.
I agree some artifacts are appearing like curvy lines etc. I also got them in [video](https://www.youtube.com/watch?v=vVkufidT0fc). I think that the network will have to be retrained with more face data and some slight change to the loss function to remove them.

**Comment by dovanchan** [comment]
Hi,I found that you can styled the Video in the demo, pretty cool!
Can you tell me how you implement that?

**Comment by gsssrao** [comment]
Try out this [repo](https://github.com/gsssrao/fast-artistic-videos) for now.

**Comment by dovanchan** [comment]
Cool,Thank you;
In my opinion，If AdaIN can improved by training more and better data,and made more flexible parameter for getting great result, AdaIN will be a best algorithm。
With taking so much time and memory in neural style,AdaIN is a great research direction
Seems all of big problem can be sloved in neural style.The only problem is the result;
What we need to do just prepared more useful data for traing! 
I am looking forward a subversive revolution in neual style
